name: Deploy to WP Engine
on:
    push:
        branches: [dev, stg, main]

jobs:
    deploy-prod:
        name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: cnoecho # WP Engine environment name
            theme_name: echo
        secrets: inherit

    deploy-stg:
        name: Deploy to Staging
        if: github.ref == 'refs/heads/stg'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: cnoechostg # WP Engine environment name
            theme_name: echo
        secrets: inherit

    deploy-dev:
        name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        uses: choctaw-nation/shared-github-actions/.github/workflows/deploy.yml@main
        with:
            WPE_ENV: cnoechodev # WP Engine environment name
            theme_name: echo
        secrets: inherit
